export enum PaystackEvent {
  ChargeDisputeCreate = "charge.dispute.create",
  ChargeDisputeRemind = "charge.dispute.remind",
  ChargeDisputeResolve = "charge.dispute.resolve",
  ChargeSuccess = "charge.success",
  CustomerIdentificationFailed = "customeridentification.failed",
  CustomerIdentificationSuccess = "customeridentification.success",
  InvoiceCreate = "invoice.create",
  InvoicePaymentFailed = "invoice.payment_failed",
  InvoiceUpdate = "invoice.update",
  PaymentRequestPending = "paymentrequest.pending",
  PaymentRequestSuccess = "paymentrequest.success",
  RefundPending = "refund.pending",
  RefundProcessing = "refund.processing",
  RefundProcessed = "refund.processed",
  RefundFailed = "refund.failed",
  SubscriptionCreate = "subscription.create",
  SubscriptionDisable = "subscription.disable",
  SubscriptionEnable = "subscription.enable",
  SubscriptionNotRenew = "subscription.not_renew",
  SubscriptionExpiringCards = "subscription.expiring_cards",
  TransferSuccess = "transfer.success",
  TransferFailed = "transfer.failed",
  TransferReversed = "transfer.reversed",
  DedicatedAccountAssignSuccess = "dedicatedaccount.assign.success",
  DedicatedAccountAssignFailed = "dedicatedaccount.assign.failed",
}

export type PaystackEventName = `${PaystackEvent}`
